# Generated by Django 4.1.7 on 2023-04-14 04:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_alter_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, default=0, related_name='post_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
