# Generated by Django 4.2.2 on 2023-06-19 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_alter_user_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='header_pic',
            field=models.ImageField(blank=True, default='defaultheader.png', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='user',
            name='link',
            field=models.URLField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
