# Generated by Django 4.2.2 on 2023-06-19 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_post_image_user_bio_user_header_pic_user_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, default='', max_length=24, null=True),
        ),
    ]
