# Generated by Django 4.2.2 on 2023-06-19 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_alter_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, default=' ', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='link',
            field=models.URLField(blank=True, default=' ', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, default=' ', max_length=24, null=True),
        ),
    ]
